version: 2.1
orbs:
  node: circleci/node@1.1.6
  cypress: cypress-io/cypress@1
jobs:
  build-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn && cd functions && npm i
            - run: yarn build
            - run: yarn add --dev firebase-tools
            - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  jobs:
    - cypress/install
    - cypress/run
  build-deploy:
    jobs:
      - build-deploy:
          filters:
            branches:
              only:
                - master
