version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn
            - run: yarn build
            - run: yarn add --dev firebase-tools
            - run: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN
workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy
          filters:
            branches:
              only: master
